export const trainingData = [
  // Pong (Atari 2600)
  {
    input: {
      year: 0.1977,
      genre_Action: 0,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 1,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Space War (Atari 2600)
  {
    input: {
      year: 0.1978,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Asteroids (Atari 2600)
  {
    input: {
      year: 0.1979,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Space Invaders (Atari 2600)
  {
    input: {
      year: 0.198,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Raiders of the Lost Ark (Atari 2600)
  {
    input: {
      year: 0.1981,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Warlords (Atari 2600)
  {
    input: {
      year: 0.1982,
      genre_Action: 0,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 1,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Mario Bros. (Atari 2600)
  {
    input: {
      year: 0.1983,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Duck Hunt (NES)
  {
    input: {
      year: 0.1984,
      genre_Action: 0,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 1,
      genre_Strategy: 0,
      genre_Sports: 1,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.02999 },
  },
  // Super Mario Bros. (NES)
  {
    input: {
      year: 0.1985,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.02999 },
  },
  // The Legend of Zelda (NES)
  {
    input: {
      year: 0.1986,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Castlevania (NES)
  {
    input: {
      year: 0.1987,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.02599 },
  },
  // World Class Track Meet (NES)
  {
    input: {
      year: 0.1988,
      genre_Action: 0,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 1,
      genre_Strategy: 0,
      genre_Sports: 1,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.02999 },
  },
  // Tetris (Game Boy)
  {
    input: {
      year: 0.1989,
      genre_Action: 0,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 1,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.02999 },
  },
  // Super Mario World (SNES)
  {
    input: {
      year: 0.199,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.03999 },
  },
  // Sonic the Hedgehog (Sega Genesis)
  {
    input: {
      year: 0.1991,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Street Fighter II (SNES)
  {
    input: {
      year: 0.1992,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Doom (PC)
  {
    input: {
      year: 0.1993,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 0,
      platform_PC: 1,
    },
    output: { price: 0.05999 },
  },
  // Mortal Kombat (Sega Genesis)
  {
    input: {
      year: 0.1994,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Donkey Kong Country (SNES)
  {
    input: {
      year: 0.1995,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05499 },
  },
  // Super Mario 64 (Nintendo 64)
  {
    input: {
      year: 0.1996,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.06499 },
  },
  // Final Fantasy VII (PlayStation)
  {
    input: {
      year: 0.1997,
      genre_Action: 0,
      genre_Adventure: 0,
      genre_RPG: 1,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // The Legend of Zelda: Ocarina of Time (Nintendo 64)
  {
    input: {
      year: 0.1998,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Half-Life (PC)
  {
    input: {
      year: 0.1999,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Metal Gear Solid (PlayStation)
  {
    input: {
      year: 0.2,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Halo: Combat Evolved (Xbox)
  {
    input: {
      year: 0.2001,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Grand Theft Auto: Vice City (PlayStation 2)
  {
    input: {
      year: 0.2002,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Prince of Persia: The Sands of Time (PlayStation 2)
  {
    input: {
      year: 0.2003,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Resident Evil 4 (GameCube)
  {
    input: {
      year: 0.2004,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Super Mario Bros. (DS)
  {
    input: {
      year: 0.2005,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.02999 },
  },
  // Wii Sports (Wii)
  {
    input: {
      year: 0.2006,
      genre_Action: 0,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 1,
      genre_Strategy: 0,
      genre_Sports: 1,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // BioShock (Xbox 360)
  {
    input: {
      year: 0.2007,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Grand Theft Auto IV (PlayStation 3)
  {
    input: {
      year: 0.2008,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // The Legend of Zelda: Twilight Princess (Wii)
  {
    input: {
      year: 0.2009,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.04999 },
  },
  // Call of Duty: Black Ops (Xbox 360)
  {
    input: {
      year: 0.201,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // The Elder Scrolls V: Skyrim (PC)
  {
    input: {
      year: 0.2011,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 1,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 1,
    },
    output: { price: 0.05999 },
  },
  // Bioshock Infinite (PlayStation 3)
  {
    input: {
      year: 0.2012,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Grand Theft Auto V (PlayStation 3)
  {
    input: {
      year: 0.2013,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // The Witcher 3: Wild Hunt (PC)
  {
    input: {
      year: 0.2014,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 1,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 0,
      platform_PC: 1,
    },
    output: { price: 0.05999 },
  },
  // Bloodborne (PlayStation 4)
  {
    input: {
      year: 0.2015,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 1,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Uncharted 4: A Thief's End (PlayStation 4)
  {
    input: {
      year: 0.2016,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // The Legend of Zelda: Breath of the Wild (Nintendo Switch)
  {
    input: {
      year: 0.2017,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Red Dead Redemption 2 (PlayStation 4)
  {
    input: {
      year: 0.2018,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 1,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Cyberpunk 2077 (PlayStation 4)
  {
    input: {
      year: 0.2019,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 1,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // The Last of Us Part II (PlayStation 4)
  {
    input: {
      year: 0.202,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Hitman 3 (PlayStation 5)
  {
    input: {
      year: 0.2021,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 1,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Elden Ring (PC)
  {
    input: {
      year: 0.2022,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 1,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 0,
      platform_PC: 1,
    },
    output: { price: 0.05999 },
  },
  // Zelda: Tears of the Kingdom (Nintendo Switch)
  {
    input: {
      year: 0.2023,
      genre_Action: 1,
      genre_Adventure: 1,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 0,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 1,
      platform_PC: 0,
    },
    output: { price: 0.05999 },
  },
  // Helldivers 2 (PC)
  {
    input: {
      year: 0.2024,
      genre_Action: 1,
      genre_Adventure: 0,
      genre_RPG: 0,
      genre_Simulation: 0,
      genre_Strategy: 1,
      genre_Sports: 0,
      genre_Puzzle: 0,
      platform_Console: 0,
      platform_PC: 1,
    },
    output: { price: 0.03999 },
  },
];
